# Generated by Django 5.0.4 on 2024-05-08 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('fk_centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centros.centros')),
            ],
        ),
    ]
