import logoTic from "/def_LOGOTIC.png";

import {
  HomeIcon,
  MapIcon,
  DocumentTextIcon,
  ServerIcon,
  ClockIcon,
  MagnifyingGlassIcon,
  ChevronRightIcon,
  BuildingOfficeIcon,
  UserIcon,
  EnvelopeIcon,
  UserCircleIcon,
  TruckIcon,
  PlusIcon,
  TrashIcon,
  UsersIcon,
  UserGroupIcon,
  UserMinusIcon,
  ShieldCheckIcon,
  EllipsisHorizontalCircleIcon,
  PencilIcon,
  GlobeAltIcon,
  BuildingLibraryIcon,
  WrenchIcon,
  DocumentIcon,
  PencilSquareIcon,
  ComputerDesktopIcon,
  NewspaperIcon,
  Bars3BottomLeftIcon,
} from "@heroicons/react/24/outline";

export const v = {
  bg_green_sena: "bg-green-600",
  logoTic,

  HomeIcon,
  MapIcon,
  DocumentTextIcon,
  ServerIcon,
  ClockIcon,
  MagnifyingGlassIcon,
  ChevronRightIcon,
  BuildingOfficeIcon,
  UserIcon,
  EnvelopeIcon,
  UserCircleIcon,
  TruckIcon,
  PlusIcon,
  TrashIcon,
  UsersIcon,
  UserGroupIcon,
  UserMinusIcon,
  ShieldCheckIcon,
  EllipsisHorizontalCircleIcon,
  PencilIcon,
  GlobeAltIcon,
  BuildingLibraryIcon,
  WrenchIcon,
  DocumentIcon,
  PencilSquareIcon,
  ComputerDesktopIcon,
  NewspaperIcon,
  Bars3BottomLeftIcon,
};
