# Generated by Django 5.0.4 on 2024-10-02 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientos', '0003_remove_mantenimiento_fecha_realizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partes_mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_nombre_repuesto', models.CharField(max_length=50)),
                ('par_costos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('par_fk_mantenimientos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimientos.mantenimiento')),
            ],
        ),
    ]
