# Generated by Django 5.0.4 on 2024-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambientes',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='ambientes.Ambientes.img'),
        ),
    ]
