# Generated by Django 5.0.4 on 2024-09-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoequipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipo',
            name='tipo_ficha',
            field=models.CharField(choices=[('equipo', 'equipo'), ('ambiente', 'ambiente')], default='equipo', max_length=20),
        ),
    ]
