# Generated by Django 5.0.4 on 2024-05-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fichas', '0002_alter_ficha_fecha_adquisicion_and_more'),
        ('tipomantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('reparacion', 'reparacion'), ('finalizado', 'finalizado')], default='finalizado', max_length=20)),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_proxima', models.DateField(auto_now=True, null=True)),
                ('fk_ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichas.ficha')),
                ('fk_tipo_mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipomantenimiento.tipomantenimiento')),
            ],
        ),
    ]
