# Generated by Django 5.0.4 on 2024-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('reparacion', 'reparacion'), ('finalizado', 'finalizado'), ('proximo', 'proximo')], default='finalizado', max_length=20),
        ),
    ]
