# Generated by Django 5.0.4 on 2024-10-02 18:23

import apps.mantenimientos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_alter_mantenimiento_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_realizacion',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='costo_final',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='ficha_soporte',
            field=models.FileField(blank=True, null=True, upload_to='mantenimiento/Pdfs/', validators=[apps.mantenimientos.models.validate_pdf]),
        ),
    ]
