# Generated by Django 5.0.4 on 2024-05-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambientes', '0001_initial'),
        ('tipoequipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_sena', models.CharField(max_length=255, unique=True)),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('fecha_adquisicion', models.DateField(auto_now=True, null=True)),
                ('fecha_inicio_garantia', models.DateField(auto_now=True, null=True)),
                ('fecha_fin_garantia', models.DateField(auto_now=True, null=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('operacion', 'operacion'), ('fuera_servicio', 'fuera_servicio'), ('reparacion', 'reparacion')], default='operacion', max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='fichas.Fichas.img')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fk_ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambientes.ambientes')),
                ('fk_tipo_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoequipo.tipoequipo')),
            ],
        ),
    ]
