# Generated by Django 5.0.4 on 2024-05-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_fin_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_inicio_garantia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
