# Generated by Django 5.0.4 on 2024-05-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_alter_ficha_fecha_adquisicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fichas.Fichas.img'),
        ),
    ]
