# Generated by Django 5.0.4 on 2024-06-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_alter_ficha_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/fichas/'),
        ),
    ]
