# Generated by Django 5.0.4 on 2024-06-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_alter_ficha_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fichas/imagen/'),
        ),
    ]
