# Generated by Django 5.0.4 on 2024-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_alter_ficha_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='fecha_adquisicion',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='fecha_fin_garantia',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='fecha_inicio_garantia',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='serial',
        ),
        migrations.AddField(
            model_name='ficha',
            name='codigoQR',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='fichaRespaldo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
