# Generated by Django 5.0.4 on 2024-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_remove_ficha_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='codigoQR',
            field=models.ImageField(blank=True, null=True, upload_to='fichas/imagenQR/'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fichaRespaldo',
            field=models.FileField(blank=True, null=True, upload_to='fichas/fichaRespaldo'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fichas/imagenEquipo/'),
        ),
    ]
