# Generated by Django 5.0.4 on 2024-10-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_alter_ficha_codigoqr_alter_ficha_ficharespaldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='codigoQR',
            field=models.ImageField(blank=True, null=True, upload_to='fichas/imagenQR'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fichas/imagenEquipo'),
        ),
    ]
