# Generated by Django 5.0.4 on 2024-05-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoequipo', '0001_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='fk_tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoequipo.tipoequipo'),
        ),
    ]
