# Generated by Django 5.0.4 on 2024-05-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_variable_fk_tipo_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='fk_tipo_equipo',
        ),
    ]
