# Generated by Django 5.0.4 on 2024-09-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoequipo', '0001_initial'),
        ('variables', '0003_remove_variable_fk_tipo_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='fk_tipo_equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoequipo.tipoequipo'),
        ),
        migrations.AddField(
            model_name='variable',
            name='var_clase',
            field=models.CharField(choices=[('obligatorias', 'obligatorias'), ('especTecnicas', 'especTecnicas'), ('seccion', 'seccion'), ('especifica', 'especifica')], default='seccion', max_length=20),
        ),
        migrations.AddField(
            model_name='variable',
            name='var_tipoDato',
            field=models.CharField(choices=[('number', 'number'), ('text', 'text'), ('date', 'date')], default='text', max_length=20),
        ),
    ]
