# Generated by Django 5.0.4 on 2024-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0004_variable_fk_tipo_equipo_variable_var_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
