# Generated by Django 5.0.4 on 2024-05-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('regional', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('sub_director', models.CharField(max_length=200)),
            ],
        ),
    ]
